networks:
  weewarnetwork:
    external: true

services:
  weewar:
    networks:
      - weewarnetwork
    build:
      context: .
      dockerfile: ./cmd/backend/Dockerfile
    volumes:
      # - ./.air.toml:/app/.air.toml:ro
      # - ./go.mod:/app/go.mod:ro
      # - ./go.sum:/app/go.sum:ro
      - ./cmd:/app/cmd
      - ./web:/app/web
      - ./protos:/app/protos
      - ./services:/app/services
      - ./utils:/app/utils
      - ./gen:/app/gen
        # command: ["air", "-c", "cmd/backend/.air.toml"]
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      WEEWAR_DB_ENDPOINT: ${WEEWAR_DB_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: service.name=onehub.backend,service.version=0.0.1
    ports:
      - 6060:6060
      - 7070:7070
      - 8080:8080
      - 9090:9090

  postgres:
    networks:
      - weewarnetwork
    image: arm64v8/postgres:16.3
      # image: postgres:15.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.data/pgdata:/var/lib/postgresql/data
        # - ./configs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf:ro
    ports:
      - 54321:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
